version: "3.9"

# 'temp'の箇所をプロジェクト名に置き換える

services:
  nginx:
    container_name: temp_nginx
    build:
      context: ./.docker/nginx
    ports:
      - '80:80'
    volumes:
      - ./server/public:/var/www/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    container_name: temp_app
    build:
      context: ./.docker/php
    ports:
        - 9000:9000
        - 5173:5173
    volumes:
      - ./server:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - /server/node_modules
      - /server/vendor
    tty: true
    depends_on:
      - db
      - redis
      - minio

  db:
    container_name: temp_db
    build: 
      context: .docker/db
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: temp_db
      MYSQL_USER: temp_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    container_name: temp_redis
    image: redis:6.0.5
    ports:
      - 6379:6379

  minio:
    container_name: temp_minio
    image: minio/minio
    ports:
      - 9999:9999
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
      MINIO_DEFAULT_BUCKETS: uploads
    command: server /export --address :9999 --console-address :9001

  # DB作成後、ER図作成したい時以外は一旦コメントアウトしておく
  # schemaspy:
  #   container_name: temp_schemaspy
  #   build: 
  #     context: .docker/schemaspy
  #   volumes:
  #     - ./server/schemaspy/output:/output
  #   depends_on:
  #     - db
  #   environment:
  #     SCHEMASPY_OUTPUT: /output